<?php 
$brands = $this->getBrands();
?>

<div class="block filter" data-bind="scope: 'compareProducts'" data-role="compare-products-sidebar">
    <div class="block-title">
        <h4 id="block-compare-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Shop By Brand');?></h4>
    </div>
    <ul class="items">
    	<?php  
	foreach (range('0', '9') as $char) :?>
		<?php if(isset($brands[$char])):?>
		<div class="brand-char-sidebar ">
<!-- 				<strong> # <?php echo $char;?></strong> -->
				<?php foreach($brands[$char] as $_brand):?>
					<li>
					<?php if($_brand->getUrlKey()):?>
					<i class="fa fa-square-o" aria-hidden="true"></i>
						<a href="<?php echo $this->getUrl('brand').$_brand->getUrlKey()?>">
						
						<?php echo __($_brand->getName());?></a>
					<?php else:?>
						<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_brand->getId()));?>">
						<i class="fa fa-square-o" aria-hidden="true"></i>
						<?php echo __($_brand->getName());?>
                                               
                                                </a>
					<?php endif;?>
					</li>
				<?php endforeach;?>
			</div>
		<?php endif;?>
	<?php endforeach;?>
	<?php  
	foreach (range('A', 'Z') as $char) :?>
		<?php if(isset($brands[$char])):?>
			<div class="brand-char-sidebar">
<!-- 				<strong> # <?php echo $char;?></strong> -->
				<?php foreach($brands[$char] as $_brand):?>
					<li>
					<?php if($_brand->getUrlKey()):?>
						<a href="<?php echo $this->getUrl('brand').$_brand->getUrlKey()?>" class="selected">
						<i class="fa fa-square-o" aria-hidden="true"></i> 
						<?php  echo __($_brand->getName());?></a>
					<?php else:?>
						<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_brand->getId()));?>">
						<i class="fa fa-square-o" aria-hidden="true"></i> 
						<?php echo __($_brand->getName());?>
                                                 <?php 
                                                //echo  "<pre>";
                                                //print_r($_brand->getData());
                                                ?>
                                                
                                                </a>
					<?php endif;?>
					</li>
				<?php endforeach;?>
			</div>
		<?php endif;?>
	<?php endforeach;?>
	</ul>
</div>
