<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if($exist = ($block->getFeaturedBrands()))
{
	//echo "hi";
	$mode = 'grid';
        $productsliderId = "12345678";
	$title = __('Popular Brands');
	 $desc = __('Choose from popular brands we offer at our shop');
	 //$items = $block->getFeaturedBrands()->getItems();
	 $items = $block->getProductCollection();
         $type = 'widget-viewed';
	$type = $type . '-' . $mode;
	//$showWishlist = true;
    //$showCompare = true;
    //$showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$description = false;
         $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
        $storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
        $currentStore = $storeManager->getStore();
        $media = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
        $linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
}
?>
<?php if ($exist): ?>
    <div style="margin-bottom: 0;" class="">
		 <div class="page-title-main">
            <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
			<p><?php /* @escapeNotVerified */ echo $desc; ?></p>
            </div>
        </div>
        <div class="block-content above-padding below-padding block widget block-new-products <?php /* @escapeNotVerified */ echo $mode; ?>">
            <?php /* @escapeNotVerified */ //echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                  <div class="slider-outer">
			<?php //echo  "<pre>";
                    //print_r($items);?>
                           <ol style="margin-bottom: 0;" class="product-widget-slider-brand products list items product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                               <?php $iterator = 1; ?>
                                                  
                                                   <?php foreach ($items as $_item): ?>
                                                           <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item product-slider"">' : '</li><li class="product-item product-slider"">' ?>
                                                            <div class="product-item-info">
                                                                <div class="product-img-main">
                                                               <?php 
                                                               $url = $this->getUrl('brand/view/',array('id'=>$_item['id']));
                                                               ?>
                                                               <a href="<?php /* @escapeNotVerified */ echo $url; ?>" class="product-item-photo">
                                                                  <?php if($_item['logo']):?>
                                                                           <img class="f-barnd-img" src="<?php echo $media.$_item['logo'] ?>" title="<?php echo $_item['name'];?>" alt="<?php echo $_item['name'];?>"/>
                                                                   <?php endif;?>
                                                               </a>
                                                           </div>
                                                           </div>
                                                                
                                                           <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                                                   <?php endforeach ?>
                                               
                           </ol>
                  </div>
				</div>
		</div>
        <script type="text/javascript" xml="space">
        require(['jquery', 'bizkickowlcarousel'], function() {
            jQuery(document).ready(function() {
                jQuery(".product-widget-slider-brand").owlCarousel({
                    items: 4,
                    itemsDesktop: [1200, 4],
					itemsDesktopSmall: [1024, 4],
					itemsTablet: [768, 3],
					itemsTabletSmall: [640, 2],
					itemsMobile: [320, 1],
                    pagination: false,
                    navigationText: ["<div class='left-arrow'><i class='fa fa-angle-left'></i></div>", "<div class='right-arrow'><i class='fa fa-angle-right'></div>"],
                    navigation: true
                });
                jQuery('.product-widget-slider-brand .product-slider').show();
            });
        });
    </script>
<?php endif; ?>