<?php
if ($exist = ($this->getBestsellerProduct() && $this->getBestsellerProduct()->getPageSize())) {
    $fet_prodcollection = $this->getBestsellerProduct();
    $productcount = $this->getProductLimit();
    $imagewidth = $this->getProductimagewidth();
    $imageheight = $this->getProductimageheight();
    $mode = 'grid';
    $title = __('Hot Sellers');
    $type = 'widget-bestseller-grid';
    $image = 'bestseller_products_content_widget_grid';

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $rating = 'short';
    $description = ($mode == 'list') ? true : false;
    $info = "";
}
$productsliderId = "abc123";
?>



<?php if ($exist): ?>
    <div class="mp-product-slider-block block  widget block-products-list <?php echo $mode; ?>">
    <?php endif; ?>
    <p class="mp-ps-info"><?php echo $info; ?></p>
</div>
<!--<div class="block widget block-bestseller-products <?php /* @escapeNotVerified */ echo $mode; ?>">-->
<style>
    .widget-bestseller-grid .owl-item li.product-item{
	width:100% !important;
}

 .widget-bestseller-grid  .owl-carousel .owl-nav.disabled,
 .widget-bestseller-grid  .owl-carousel .owl-dots.disabled {
    display: block; }
 
   
</style>
<div class="block-content product-slider-wrapper">
	<div class="block-title">
            <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
    <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
    <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
        <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">                
            <?php $iterator = 1; ?>
            <div class="owl-carousel" id="mageplaza-product-slider-<?php echo $productsliderId; ?>">
                <?php
                foreach ($fet_prodcollection as $item):

                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getProductId());
                    ?>


                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                    <div class="product-item-info">
                        <?php
                        $image_url = $block->imageHelperObj()->init($_product, 'product_base_image')
                                ->setImageFile($_product->getFile())
//                                ->resize($imagewidth, $imageheight)
                                ->getUrl();
                        ?>
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-item-photo">
                            <img src="<?php echo $image_url; ?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
                        </a>
                        <div class="product-item-details">
                            <strong class="mp-product-item-name">
                                <a title="<?php echo $block->escapeHtml($_product->getName()) ?>"
                                   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
                                   class="product-item-link">
                                       <?php echo $block->escapeHtml($_product->getName()) ?>
                                </a>
                            </strong>
                            <?php
                            echo $this->getProductPriceHtml($_product, $type);
                            ?>

                            <div class="product-item-actions">

                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                            <button class="action tocart primary"
                                                    data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product) ?>"}}'
                                                    type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getId()]);
                                            ?>
                                            <button class="action tocart primary"
                                                    data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                    type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>

                                <!--===============================================-->
                                <?php if ($showWishlist || $showCompare): ?>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                            <a href="#"
                                               class="action towishlist" data-action="add-to-wishlist"
                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($item); ?>'
                                               title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                            <a href="#" class="action tocompare"
                                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($item); ?>'
                                               title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                <!--===============================================-->
                            </div>

                        </div>    
                    </div>
                    <?php echo($iterator == count($fet_prodcollection) + 1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </div>
        </ol>
    </div>
    <?php echo $block->getPagerHtml() ?>
</div>
<script>
    require([
        'jquery',
        'Mageplaza_Productslider/js/owl.carousel.min'
    ], function ($) {
        $('#mageplaza-product-slider-<?php echo $productsliderId; ?>').owlCarousel({is_enabled: 1, loop: 1, responsive: {0: {items: 1}, 600: {items: 3}, 1000: {items: 5}}, number_items_slider_screen_size_0: 1, number_items_slider_screen_size_600: 3, number_items_slider_screen_size_1000: 5, margin: 10, autoWidth: 0, nav: 1, navText: ['next', 'prev'], dots: 1, lazyLoad: 1, autoplay: 1, autoplayTimeout: 1000, });
    });
</script>
<?php // endif; ?>

