<?php
	/**
		* Copyright © 2013-2017 Magento, Inc. All rights reserved.
		* See COPYING.txt for license details.
	*/
	
	// @codingStandardsIgnoreFile
?>
<?php
	/** @var $block \Magento\Framework\View\Element\Template */
	/** @var $helper \Magento\Search\Helper\Data */
	$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block block-search1">
    <div class="block block-title1 hidden"><strong><?php /* @escapeNotVerified */ echo __('Search Within'); ?></strong></div>
    <div class="block block-content1">
        <form class="form minisearch" id="search_mini_form_list" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <div class="control">
                    <input id="search_list"
					data-mage-init='{"quickSearch":{
					"formSelector":"#search_mini_form_list",
					"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
					"destinationSelector":"#search_autocomplete_list"}
					}'
					type="text"
					name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
					value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
					placeholder="<?php /* @escapeNotVerified */ echo __('Search Within'); ?>"
					class="input-text"
					maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
					role="combobox"
					aria-haspopup="false"
					aria-autocomplete="both"
					autocomplete="off"/>
                    <div id="search_autocomplete_list" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
				</div>
			</div>
			<div class="actions">
				<button type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>" class="action search btn-search1" disabled>
					<i class="fa fa-search"></i>
				</button>
				<span><?php /* @escapeNotVerified */ //echo __('Search'); ?></span>
			</div>
		</form>
	</div>
</div>
