<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();
if ($_attributeLabel && $_attributeLabel == 'default') {
$_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
$_attributeValue =$_product->getResource()->getAttribute($_code)->getFrontend()->getValue($_product);

 $url = $_product->getVideo();
    preg_match('/[\\?\\&]v=([^\\?\\&]+)/', $url, $matches);
	if(isset($matches[1])) $id = $matches[1];

?>

<?php if ($_attributeValue): ?>
<div>
<?php if ($_attributeLabel != 'none'): ?><?php endif; ?>
<div class="value" <?php //echo $_attributeAddAttribute;?>><?php //echo $_attributeValue; ?></div>
</div>
<?php //echo "video:".$_product->getVideo();?>

<div class="yt-video-container" id="ytVideo">
	<iframe src="https://www.youtube.com/embed/<?php echo $id ?>"frameborder="0" allowfullscreen class="yt-video"></iframe>
</div>


<?php endif; ?>