<?php //$items = $block->getItems() ?>
<table class="email-items">
    <thead>
        <tr>
            <th class="item-info">
                <?= /* @escapeNotVerified */  __('Items555555555555555'); ?>
            </th>
            <th class="item-qty">
                <?= /* @escapeNotVerified */  __('Qty1111111111111111'); ?>
            </th>
            <th class="item-price">
                <?= /* @escapeNotVerified */  __('Price333333333333333333'); ?>
            </th>
        </tr>
    </thead>
    <tbody>
    <?php /* foreach ($_items as $_item): ?>
        <tr>
            <td>$item->getName()</td>
            <td>$item->getSku()</td>
            <td>$item->getPrice()</td>
        </tr>
    <?php endforeach; */ ?>
    </tbody>
</table>