<?php

// @codingStandardsIgnoreFile
/**
 * @var \CyberSource\PayPal\Block\Express\Form $block
 * @see \CyberSource\PayPal\Block\Express\Form
 */
$code = $block->escapeHtml($block->getBillingAgreementCode());
?>
<fieldset class="fieldset paypal items redirect" style="display:none;"
          id="payment_form_<?= $block->escapeHtml($block->getMethodCode()) ?>">
    <div><?= $block->escapeHtml($block->getRedirectMessage()) ?></div>
</fieldset>
