<?php
	
	// Adding transaction in debug.log	
	\Magento\Framework\App\ObjectManager::getInstance()->get('Psr\Log\LoggerInterface')->debug("Success.phtml Called");
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	
	$orderIncrementId = $objectManager->create('\Magento\Sales\Model\ResourceModel\Order\Collection')->getLastItem()->getIncrementId();
	\Magento\Framework\App\ObjectManager::getInstance()->get('Psr\Log\LoggerInterface')->debug(print_r(['Order Success Id' => $orderIncrementId], true));
	$order = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($orderIncrementId);
	$amount = round( $order->getGrandTotal(), 3 );
	
	?>
	<div class="checkout-success" style="text-align:center;">
		<div class="page-title" style="text-align:center;">
			<h1 style="text-align:center;"><?php echo __('Your order has been received.') ?></h1>
		</div>
		<h2 class="sub-title" style="text-align:center;"><?php echo __('Thank you for your purchase!') ?></h2>
		<p style="text-align:center;"><?php echo __('Your order # is: <span>%1</span>.', $orderIncrementId) ?></p>
		<p style="text-align:center;"><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
		<?php
		if(array_key_exists('PaymentID', $_GET))
		{
			\Magento\Framework\App\ObjectManager::getInstance()->get('Psr\Log\LoggerInterface')->debug(print_r(['Get Variables' => $_GET], true));
			$paymentID = $_GET['PaymentID'];
			$presult = $_GET['Result'];
			$postdate = $_GET['PostDate'];
			$tranid = $_GET['TranID'];
			$auth = $_GET['Auth'];
			$ref = $_GET['Ref'];
			$trackid = $_GET['TrackID'];
			
			$message = '<strong>KNET Payment Details:</strong><br/><br/>'; 
			$message .= 'PaymentID: ' . $paymentID . "<br/>";
			$message .= 'Amount: ' . $amount . "<br/>";
			$message .= 'Result: ' . $presult . "<br/>";
			$message .= 'PostDate: ' . $postdate . "<br/>";
			$message .= 'TranID: ' . $tranid . "<br/>";
			$message .= 'Auth: ' . $auth . "<br/>";
			$message .= 'Ref: ' . $ref . "<br/>";
			$message .= 'TrackID: ' . $trackid . "<br/>";
			$message .= 'Time: ' . date('H:i:s') . "<br/>";
			echo $message;
		}
		?>
		<div class="actions-toolbar" style="text-align:center; margin:0 auto; width:220px;">
			<div class="primary" style="text-align:center;">
				<a style="text-align:center;" class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span style="text-align:center;"><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
			</div>
		</div>
	</div>
