<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
?>
<?php
//Fetch custom city and state  value start
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('city');
$sql1 = "Select * FROM " . $tableName;
$cityresult = $connection->fetchAll($sql1);
$cityattributesArrays = array();
foreach ($cityresult as $alldata) {
    $cityattributesArrays[$alldata['id']] = array(
        'city_name' => $alldata['city_name'],
        'state_id' => $alldata['state_id']
    );
}

$statetableName = $resource->getTableName('directory_country_region');
$sqlstate = "SELECT * FROM  " . $statetableName . " where country_id = 'KW' ";
$stateresult = $connection->fetchAll($sqlstate);


$stateattributesArrays = array();
foreach ($stateresult as $allstatedata) {
    $stateattributesArrays[$allstatedata['region_id']] = array(
        'region_id' => $allstatedata['region_id'],
        'country_id' => $allstatedata['country_id'],
        'code' => $allstatedata['code'],
        'default_name' => $allstatedata['default_name'],
    );
}
//Fetch custom city and state  value start
?>
<form class="form-address-edit" action="<?php /* @escapeNotVerified */ echo $block->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span></legend><br>
        <?php echo $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
        <?php echo $block->getNameBlockHtml() ?>
        <div class="field company">
            <label class="label" for="company"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
            <div class="control">
                <input type="text" name="company" id="company" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getCompany()) ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
            </div>
        </div>
        <div class="field telephone required">
            <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
            <div class="control">
                <input type="text" name="telephone" value="<?php echo $block->escapeHtml($block->getAddress()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>" id="telephone" min="8" max="8">
            </div>
        </div>
        <div class="field fax">
            <label class="label" for="fax"><span><?php /* @escapeNotVerified */ echo __('Fax') ?></span></label>
            <div class="control">
                <input type="text" name="fax" id="fax" title="<?php /* @escapeNotVerified */ echo __('Fax') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getFax()) ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('fax') ?>">
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></legend><br>
        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
            <div class="control">
                <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine(1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>"  />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i + 1 ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Street Address %1', $_i + 1) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getStreetLine($_i + 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i + 1) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i + 1 ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id"><span><?php /* @escapeNotVerified */ echo __('VAT Number') ?></span></label>
                <div class="control">
                    <input type="text" name="vat_id" value="<?php echo $block->escapeHtml($block->getAddress()->getVatId()) ?>" title="<?php /* @escapeNotVerified */ echo __('VAT Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id') ?>" id="vat_id">
                </div>
            </div>
        <?php endif; ?>
        <div class="field city required">
            <label class="label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span><span><?php /* @escapeNotVerified */ echo __('(Please Select State first)') ?></span></label>
            <div class="control">
                <?php
                $select = "select=selected";
                ?>
                <select id="city" name="city" title="<?php /* @escapeNotVerified */ echo __('city') ?>" class="validate-select" >
                    <option value=""><?php /* @escapeNotVerified */ echo __('Please Select City') ?></option>
                    <?php if( $block->escapeHtml($block->getRegionId() != '')){ ?>
                    <?php
                    foreach ($cityresult as $alldata) {
                        ?>
                        <option value="<?= $alldata['city_name']; ?>" <?php if ($alldata['city_name'] == $block->getAddress()->getCity()) {
                        echo($select);
                    } ?>><?= $alldata['city_name']; ?></option>
                        <?php
                    }
                    
                     } 
                    ?>

                </select>
                <input type="hidden" id="citydbdata" name="citydbdata" value="<?php echo $block->getAddress()->getCity(); ?>"  />
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
            <div class="control">
                <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : ''; ?>>
                    <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>"  title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : ''; ?>/>
                <input type="hidden" id="stateregion" name="stateregion" value="<?php echo $block->escapeHtml($block->getRegionId()) ?>"  />
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
            <div class="control">
                <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getAddress()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
            <div class="control">
<?php echo $block->getCountryHtmlSelect() ?>
            </div>
        </div>

        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default billing address.") ?></div>
<?php elseif ($block->canSetAsDefaultBilling()): ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                <label class="label" for="primary_billing"><span><?php /* @escapeNotVerified */ echo __('Use as my default billing address') ?></span></label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default shipping address.") ?></div>
<?php elseif ($block->canSetAsDefaultShipping()): ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                <label class="label" for="primary_shipping"><span><?php /* @escapeNotVerified */ echo __('Use as my default shipping address') ?></span></label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1">
<?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save Address') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>

</form>
<script type="text/x-magento-init">
    {
    "#form-validate": {
    "validation": {}
    },
    "#country": {
    "regionUpdater": {
    "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
    "regionListId": "#region_id",
    "regionInputId": "#region",
    "postcodeId": "#zip",
    "form": "#form-validate",
    "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
    "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId() ?>",
    "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
    }
    }


    }
</script>
<script >
jQuery(window).load(function () {
        if (jQuery('#stateregion').val() != '') {
            stateval = jQuery('#stateregion').val();
            var cityId = jQuery('[name="city"]:eq(0)').attr('id');
            populateCitySelect(stateval, cityId);
            var cityval = jQuery('#citydbdata').val();
            jQuery('select[name^="city"] option[value="' + cityval + '"]').attr("selected", "selected");

        }
    });
    jQuery(document).ready(function () {
        jQuery(document).on('change', "[name='region_id']", function () {
            stateval = jQuery(this).val();
           
            var cityId = jQuery('[name="city"]:eq(0)').attr('id');
            
        if(stateval == ""){
             jQuery('#' + cityId).html('');
             jQuery('#' + cityId).append('<option value=""  >Please Select City.</option>');
        }else{
           
            populateCitySelect(stateval, cityId);
        }
        });
    });
    function populateCitySelect(sval, cityId) {
     
        var cityOptionObject = JSON.stringify(<?php /* @escapeNotVerified */ echo json_encode($cityattributesArrays); ?>);
        var TESTObject = JSON.parse(cityOptionObject);
        var cityData = [];
        for (var x in TESTObject) {
            cityData.push(TESTObject[x]);
        }

        var stateOptionObject = JSON.stringify(<?php /* @escapeNotVerified */ echo json_encode($stateattributesArrays); ?>);

        var stateObject = JSON.parse(stateOptionObject);
        var stateData = [];
        for (var x in stateObject) {
            stateData.push(stateObject[x]);
        }

        jQuery.each(stateData, function (index, statedata) {
            var finalcityData = [];
            if (sval == statedata['region_id']) {
                jQuery.each(cityData, function (index, citydata) {
                    if (statedata['code'] == citydata['state_id']) {

                        finalcityData.push(citydata['city_name']);
                    }
                });
                jQuery('#' + cityId).html('');

                jQuery('#' + cityId).append('<option value=""  >Please Select City.</option>');
                finalcityData.forEach(function (t) {
                    jQuery('#' + cityId).append('<option value="' + t + '">' + t + '</option>');
                });

            }

        });
    }
</script>


