<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<div>
        <?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
	//echo '</pre>'; print_r($block->getData()); 
	if($title=="Hot Sellers")
	{
    $desc = __('Find the perfect toy always in demand');
	}
	else if($title=="Featured Collection"){
			  $desc = __('Find out our outstanding featured collection');
		}
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$objectMana = \Magento\Framework\App\ObjectManager::getInstance();
    $description = false;
    ?>
    <div class="owl-button-top block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($title): ?>
            <div class="page-title-main">
                <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
				<p><?php /* @escapeNotVerified */ echo $desc; ?></p>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <div class="slider-outer">
                     
                     <ol style="margin-bottom: 0;" class="product-widget-slider-attribute products list items product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                        <?php $iterator = 1; ?>
                         
                        <?php foreach ($items as $_item): ?>
						 
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-slider product-item">' : '</li><li class="product-slider product-item">' ?>
                            <div class="product-item-info">
                                <div class="product-img-main">
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                    </a>
                                    <div class="product-item-inner">
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="product actions product-item-actions">
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                           class="product-item-link">
                                               <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
									<p class="product-item-category"><?php 
                        $product = $objectMana->create('Magento\Catalog\Model\Product')->load($_item->getEntityId());
                        $categoryIds = $product->getCategoryIds();
                        if(count($categoryIds) ){
                              if(count($categoryIds) > 1){
                                  $firstCategoryId = $categoryIds[1];
                              }else{
                                  $firstCategoryId = $categoryIds[0];
                              }
//                            $firstCategoryId = $categoryIds[1];
                            $object_manager = $objectMana->create('Magento\Catalog\Model\Category')->load($firstCategoryId);
                            echo $object_manager->getName();
                         }
                        ?></p>
                                    <?php
                                    echo $block->getProductPriceHtml($_item, $type);
                                    ?>

                                    <?php if ($templateType): ?>
                                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product-item-inner">
                                            <div class="product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                <button class="action tocart primary add-to-cart-img"
                                                                        data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span>&nbsp;<?php /* @escapeNotVerified */ //echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php
                                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <button class="action tocart primary add-to-cart-img"
                                                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span>&nbsp;<?php /* @escapeNotVerified */ //echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                                    <?php endif; ?>
                                                                <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php echo($iterator == count($items) + 1) ? '</li>' : '' ?>
                        
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>

   <script type="text/javascript" xml="space">
        require(['jquery', 'bizkickowlcarousel'], function() {
            jQuery(document).ready(function() {
                jQuery(".product-widget-slider-attribute").owlCarousel({
                    items: 3,
                    itemsDesktop: [1200, 2],
                    itemsDesktopSmall: [1200, 2],
                    itemsTablet: [992, 1],
                    itemsTabletSmall: [992, 1],
                    itemsMobile: [768, 1],
                    pagination: false,
                    navigationText: ["<div class='left-arrow'><i class='fa fa-angle-left'></i></div>", "<div class='right-arrow'><i class='fa fa-angle-right'></div>"],
                    navigation: true,
					slideSpeed : 200,
					paginationSpeed : 800,
					rewindSpeed : 1000,
					loop:true
                });
                jQuery('.product-widget-slider-attribute .product-slider').show();
            });
        });
    </script>

     
    
<?php endif; ?>
    </div>
</div>

