<?php 
$age_groupList = $block->getOptionlist('age_group');
$genderList = $block->getOptionlist('gender');
//$priceList = $block->getOptionlist('price');
$objectManagerlogin = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManagerlogin->get('Magento\Customer\Model\Session');
$baseurl = $objectManagerlogin->get('Magento\Store\Model\StoreManagerInterface')->getStore(0)->getBaseUrl();
?>

<?php 
$url = $baseurl."layerworld/index/result";
$select="selected=selected";
?>
    <form class="form layarsearch" id="search_layarsearch_list1" action="<?php echo $url;?>" method="get">
        <div class="block filter mana-filter-block gift-finder-dropdown" id="layerfilter-block-layernavigation">
        <div class="block-content filter-content">
            <div class="filter-options" id="narrow-by-list">
				<h2 class="title-gf"><?php echo __('Gift Finder') ?></h2>
                 <div class="form-group">
                    <label><?php echo __('Age Group') ?></label>
                    <select name="age_group" role="heading" aria-level="3" class="form-control">
                         <option value="" ><?php echo __('Select Age Group') ?></option> 
                         <?php foreach ($age_groupList as $item) : ?>
                                <option  value="<?php echo $item['value']; ?>" <?php if( $this->getRequest()->getParam('age_group') == $item['value'] ) { echo($select); }?> ><?php echo $item['label']; ?></option> 
                         <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label><?php echo __('Gender') ?></label>
                    <select name="gender" role="heading" aria-level="3" class="form-control">
                        <option value="" ><?php echo __('Select Gender') ?></option> 
                         <?php foreach ($genderList as $item) : ?>
                                <option  value="<?php echo $item['value']; ?>" <?php if( $this->getRequest()->getParam('gender') == $item['value'] ) { echo($select); }?> ><?php echo $item['label']; ?></option> 
                         <?php endforeach; ?>
                    </select>
                </div>
                 <div class="form-group">
                    <label><?php echo __('Select Price') ?></label>
								   <select name="price" role="heading" aria-level="3" class="additional-filter-price form-control">
										<option value="" ><?php echo __('Select Price') ?></option> 
                                                                                <option  value="-100" <?php if( $this->getRequest()->getParam('price') == '-100' ) { echo($select); }?> ><?php echo __('Below KWD 100.000');?></option> 
                                                                                <option  value="100-200" <?php if( $this->getRequest()->getParam('price') == '100-200' ) { echo($select); }?> ><?php echo __('KWD 100.000 - KWD 200.000');?></option> 
                                                                                <option  value="200-300" <?php if( $this->getRequest()->getParam('price') == '200-300' ) { echo($select); }?>><?php echo __('KWD 200.000 - KWD 300.000');?></option> 
                                                                                <option  value="300-400" <?php if( $this->getRequest()->getParam('price') == '300-400' ) { echo($select); }?>><?php echo __('KWD 300.000 - KWD 400.000');?></option> 
                                                                                <option  value="400-500" <?php if( $this->getRequest()->getParam('price') == '400-500' ) { echo($select); }?>><?php echo __('KWD 400.000 - KWD 500.000');?></option> 
                                                                                <option  value="500-600" <?php if( $this->getRequest()->getParam('price') == '500-600' ) { echo($select); }?> ><?php echo __('KWD 500.000 - KWD 600.000');?></option> 
                                                                                <option  value="600-700" <?php if( $this->getRequest()->getParam('price') == '600-700' ) { echo($select); }?>><?php echo __('KWD 600.000 - KWD 700.000');?></option> 
                                                                                <option  value="800-900" <?php if( $this->getRequest()->getParam('price') == '800-900' ) { echo($select); }?>><?php echo __('KWD 800.000 - KWD 900.000');?></option> 
                                                                                <option  value="900-" <?php if( $this->getRequest()->getParam('price') == '900-' ) { echo($select); }?>><?php echo __('KWD 900.000 and above');?></option> 
									 </select>
                </div>
         
            </div>
            <button type="submit"  title="<?php echo $block->escapeHtml(__('Search')) ?>" class="action search btn-gf">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
            </button>
        </div>	
    </div>

    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
    
    </form>



