<?php 
$age_groupList = $block->getOptionlist('age_group');
$genderList = $block->getOptionlist('gender');
//$priceList = $block->getOptionlist('price');
$objectManagerlogin = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManagerlogin->get('Magento\Customer\Model\Session');
$baseurl = $objectManagerlogin->get('Magento\Store\Model\StoreManagerInterface')->getStore(0)->getBaseUrl();
?>

<?php 
$url = $baseurl."layerworld/index/result";
$select="selected=selected";
?>
    <form class="form layarsearch" id="search_layarsearch_list1" action="<?php echo $url;?>" method="get">
        <div class="block filter mana-filter-block gift-finder-dropdown" id="layerfilter-block-layernavigation">
        <div class="block-content filter-content">
            <div class="filter-options" id="narrow-by-list">
				<h2 class="title-gf"><?php echo __('Gift Finder') ?></h2>
                 <div class="form-group">
                    <label><?php echo __('Age Group') ?></label>
                    <select name="age_group" role="heading" aria-level="3" class="form-control">
                        <option value="null" selected="selected"><?php echo __('Select Age Group') ?></option> 
                         <?php foreach ($age_groupList as $item) : ?>
                         <?php 
                                    if($item['label'] == 'ALL AGES')
                                    {
                                        $item['value'] = '';
										$select='';
                                    }
									
                                ?>
                                <option  value="<?php echo $item['value']; ?>" <?php if( $this->getRequest()->getParam('age_group') == $item['value'] ) { echo($select); }?> ><?php echo $item['label']; ?></option> 
                                
                         <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
					<?php $select="selected=selected";?>
                    <label><?php echo __('Gender') ?></label>
                    <select name="gender" role="heading" aria-level="3" class="form-control">
                        <option value="" ><?php echo __('Select Gender') ?></option> 
                         <?php foreach ($genderList as $item) : ?>
                                <option  value="<?php echo $item['value']; ?>" <?php if( $this->getRequest()->getParam('gender') == $item['value'] ) { echo($select); }?> ><?php echo $item['label']; ?></option> 
                         <?php endforeach; ?>
                    </select>
                </div>
                 <div class="form-group">
                    <label><?php echo __('Select Price') ?></label>
								   <select name="price" role="heading" aria-level="3" class="additional-filter-price form-control">
										<option value="" ><?php echo __('Select Price') ?></option> 
                                                                                <option  value="-25" <?php if( $this->getRequest()->getParam('price') == '-25' ) { echo($select); }?> ><?php echo __('KWD 0.000 - KWD 25.000 ');?></option> 
                                                                                <option  value="25-50" <?php if( $this->getRequest()->getParam('price') == '25-50' ) { echo($select); }?> ><?php echo __('KWD 25 .000 - KWD 50.000');?></option> 
                                                                                <option  value="50-75" <?php if( $this->getRequest()->getParam('price') == '50 - 75' ) { echo($select); }?>><?php echo __('KWD 50 .000 - KWD 75.000');?></option> 
                                                                                <option  value="75-100" <?php if( $this->getRequest()->getParam('price') == '75 - 100' ) { echo($select); }?>><?php echo __('KWD 75.000 - KWD 100.000');?></option>
                                                                                <option  value="100-" <?php if( $this->getRequest()->getParam('price') == '100-' ) { echo($select); }?>><?php echo __('KWD 100.000 and above');?></option> 
									 </select>
                </div>
         
            </div>
            <button type="submit"  title="<?php echo $block->escapeHtml(__('Search')) ?>" class="action search btn-gf">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
            </button>
        </div>	
    </div>

    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
    
    </form>



